version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - user_service_network    
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:  
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "user-events" 
    networks:
      - user_service_network     
      
  dbservice:
    image: mysql:8.0.21
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=localpassword@2023
      - MYSQL_PASSWORD=localpassword@2023
      - DATABASE_NAME=event_campaign
      
    volumes:
      - ./data:/var/lib/mysql
      
    ports:
      - 3307:3306  
    networks:
      - user_service_network  
    
  app:
    build: .
    environment: 
      - spring.datasource.url = jdbc:mysql://dbservice:3306/user_data?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      - spring.datasource.username = root
      - spring.datasource.password = localpassword@2023   
    depends_on: 
      - dbservice
    
    ports:
      - 8080:8080  
    networks:
      - user_service_network 
      
networks: 
  user_service_network:                  
       